import { useAppTheme } from "@/hooks/useAppTheme";
import type { SVGProps } from "react";

export const HomepageHeroLargeBg = (props: SVGProps<SVGSVGElement>) => {
  const { isDarkMode } = useAppTheme();

  const strokeColor = isDarkMode ? "rgba(252, 252, 251)" : "rgba(17, 17, 17)";

  return (
    <svg
      fill="none"
      viewBox="0 0 1440 600"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <mask
        height="100%"
        id="mask0_45_8736"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
        width="100%"
        x="0"
        y="0"
      >
        <path
          d="M1440 360H1320V480H1200V600H240V480H120V360H0V0H1440V360Z"
          fill="currentColor"
        />
      </mask>
      <g mask="url(#mask0_45_8736)">
        <g filter="url(#filter0_f_45_8736)">
          <ellipse
            cx="592.5"
            cy="693"
            fill="url(#paint0_radial_45_8736)"
            rx="329.5"
            ry="332"
          />
        </g>
        <g filter="url(#filter1_f_45_8736)">
          <ellipse
            cx="848.5"
            cy="613"
            fill="url(#paint1_radial_45_8736)"
            rx="329.5"
            ry="332"
          />
        </g>
      </g>
      <g clipPath="url(#clip0_45_8736)">
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          y="120"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          y="240"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="120"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="120"
          y="120"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="120"
          y="240"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="120"
          y="360"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="240"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="240"
          y="120"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="240"
          y="240"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="240"
          y="360"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="240"
          y="480"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="360"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="360"
          y="120"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="360"
          y="240"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="360"
          y="360"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="360"
          y="480"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="480"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="480"
          y="120"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="480"
          y="240"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="480"
          y="360"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="480"
          y="480"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="600"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="600"
          y="120"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="600"
          y="240"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="600"
          y="360"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="600"
          y="480"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="720"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="720"
          y="120"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="720"
          y="240"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="720"
          y="360"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="720"
          y="480"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="840"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="840"
          y="120"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="840"
          y="240"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="840"
          y="360"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="840"
          y="480"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="960"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="960"
          y="120"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="960"
          y="240"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="960"
          y="360"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="960"
          y="480"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="1080"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="1080"
          y="120"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="1080"
          y="240"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="1080"
          y="360"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="1080"
          y="480"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="1200"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="1200"
          y="120"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="1200"
          y="240"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="1200"
          y="360"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="1320"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="1320"
          y="120"
        />
        <rect
          height="120"
          opacity="0.5"
          stroke={strokeColor}
          strokeOpacity="0.1"
          width="120"
          x="1320"
          y="240"
        />
      </g>
    </svg>
  );
};

export const HomepageHeroLargeRadial = (props: SVGProps<SVGSVGElement>) => {
  return (
    <svg
      fill="none"
      viewBox="0 0 1440 600"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <defs>
        <filter
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
          height="1264"
          id="filter0_f_45_8736"
          width="1259"
          x="-37"
          y="61"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            mode="normal"
            result="shape"
          />
          <feGaussianBlur
            result="effect1_foregroundBlur_45_8736"
            stdDeviation="150"
          />
        </filter>
        <filter
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
          height="1464"
          id="filter1_f_45_8736"
          width="1459"
          x="119"
          y="-119"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            mode="normal"
            result="shape"
          />
          <feGaussianBlur
            result="effect1_foregroundBlur_45_8736"
            stdDeviation="200"
          />
        </filter>
        <radialGradient
          cx="0"
          cy="0"
          gradientTransform="translate(592.5 693) rotate(90) scale(332 329.5)"
          gradientUnits="userSpaceOnUse"
          id="paint0_radial_45_8736"
          r="1"
        >
          <stop stopColor="#2DB8CF" />
          <stop offset="1" stopColor="#2DB8CF" stopOpacity=".5" />
        </radialGradient>
        <radialGradient
          cx="0"
          cy="0"
          gradientTransform="translate(848.5 613) rotate(90) scale(332 329.5)"
          gradientUnits="userSpaceOnUse"
          id="paint1_radial_45_8736"
          r="1"
        >
          <stop stopColor="#B8FFE3" />
          <stop offset="1" stopColor="#2DB8CF" stopOpacity=".5" />
        </radialGradient>
        <clipPath id="clip0_45_8736">
          <rect fill="white" height="600" width="1440" />
        </clipPath>
      </defs>
    </svg>
  );
};
