import { useAppTheme } from "@/hooks/useAppTheme";
import type { SVGProps } from "react";

export const HomepageHeroSmallBg = (props: SVGProps<SVGSVGElement>) => {
  const { isDarkMode } = useAppTheme();

  const strokeColor = isDarkMode ? "rgba(252, 252, 251)" : "rgba(17, 17, 17)";

  return (
    <svg
      fill="none"
      viewBox="0 0 393 550"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <g clipPath="url(#clip0_45_8936)">
        <path
          d="M581.5 330.029L471.366 329.726V439.726H361.5V549.726L31.5 549.598V439.598H-78.5V329.598H-188.366L-188.5 0L581.366 0.431357L581.5 330.029Z"
          fill="currentColor"
          stroke={strokeColor}
          strokeOpacity="0.1"
        />
        <mask
          height="552"
          id="mask0_45_8936"
          maskUnits="userSpaceOnUse"
          style={{ maskType: "alpha" }}
          width="772"
          x="-189"
          y="-1"
        >
          <path
            d="M582 330.194L471.866 329.89V439.945H362V550L32 549.872V439.818H-78V329.763H-187.866L-188 0L581.866 0.431572L582 330.194Z"
            fill="currentColor"
            stroke={strokeColor}
            strokeOpacity="0.2"
          />
        </mask>
        <g mask="url(#mask0_45_8936)">
          <g filter="url(#filter0_f_45_8936)">
            <ellipse
              cx="99.5"
              cy="475.5"
              fill="url(#paint0_radial_45_8936)"
              rx="178"
              ry="179.5"
            />
          </g>
          <g filter="url(#filter1_f_45_8936)">
            <ellipse
              cx="309.5"
              cy="432.5"
              fill="url(#paint1_radial_45_8936)"
              rx="178"
              ry="179.5"
            />
          </g>
        </g>
        <g clipPath="url(#clip1_45_8936)">
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="-78.5"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="-78.5"
            y="110"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="-78.5"
            y="220"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="-78.5"
            y="330"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="31.5"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="31.5"
            y="110"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="31.5"
            y="220"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="31.5"
            y="330"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="31.5"
            y="440"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="141.5"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="251.5"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="141.5"
            y="110"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="251.5"
            y="110"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="141.5"
            y="220"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="251.5"
            y="220"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="141.5"
            y="330"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="251.5"
            y="330"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="141.5"
            y="440"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="251.5"
            y="440"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="361.5"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="361.5"
            y="110"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="361.5"
            y="220"
          />
          <rect
            height="110"
            opacity="0.5"
            stroke={strokeColor}
            strokeOpacity="0.1"
            width="110"
            x="361.5"
            y="330"
          />
        </g>
      </g>
    </svg>
  );
};

export const HomepageHeroSmallRadial = (props: SVGProps<SVGSVGElement>) => {
  return (
    <svg
      fill="none"
      viewBox="0 0 393 550"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <defs>
        <filter
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
          height="659"
          id="filter0_f_45_8936"
          width="656"
          x="-228.5"
          y="146"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            mode="normal"
            result="shape"
          />
          <feGaussianBlur
            result="effect1_foregroundBlur_45_8936"
            stdDeviation="75"
          />
        </filter>
        <filter
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
          height="759"
          id="filter1_f_45_8936"
          width="756"
          x="-68.5"
          y="53"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            mode="normal"
            result="shape"
          />
          <feGaussianBlur
            result="effect1_foregroundBlur_45_8936"
            stdDeviation="100"
          />
        </filter>
        <radialGradient
          cx="0"
          cy="0"
          gradientTransform="translate(99.5 475.5) rotate(90) scale(179.5 178)"
          gradientUnits="userSpaceOnUse"
          id="paint0_radial_45_8936"
          r="1"
        >
          <stop stopColor="#2DB8CF" />
          <stop offset="1" stopColor="#2DB8CF" stopOpacity="0.5" />
        </radialGradient>
        <radialGradient
          cx="0"
          cy="0"
          gradientTransform="translate(309.5 432.5) rotate(90) scale(179.5 178)"
          gradientUnits="userSpaceOnUse"
          id="paint1_radial_45_8936"
          r="1"
        >
          <stop stopColor="#B8FFE3" />
          <stop offset="1" stopColor="#2DB8CF" stopOpacity="0.5" />
        </radialGradient>
        <clipPath id="clip0_45_8936">
          <rect
            fill="white"
            height="549.726"
            transform="translate(-188.5)"
            width="770"
          />
        </clipPath>
        <clipPath id="clip1_45_8936">
          <rect
            fill="white"
            height="600"
            transform="translate(-188.5)"
            width="770"
          />
        </clipPath>
      </defs>
    </svg>
  );
};
