packages:
  - name: v1
    functions:
      - name: newsletter
        runtime: nodejs:22
        web: true
        limits:
          timeout: 10000
          memory: 512
      - name: contact
        runtime: nodejs:22
        web: true
        limits:
          timeout: 10000
          memory: 512
