import { PageFooter } from "@/components/PageFooter/PageFooter";
import {
  cn,
  geist,
  geistMono,
  loadCtaBlockData,
  loadFooterData,
} from "@/utils";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const ctaBlockDData = loadCtaBlockData();
  const footerData = loadFooterData();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(geist.variable, geistMono.variable, "antialiased")}>
        <ThemeProvider
          attribute="data-theme"
          defaultTheme="light"
          enableSystem
          themes={["light", "dark"]}
        >
          {children}
          {ctaBlockDData && footerData && (
            <PageFooter
              ctaBlockProps={ctaBlockDData}
              footerProps={footerData}
            />
          )}
        </ThemeProvider>
      </body>
    </html>
  );
}
